### ISSUE TITLE
C stack error on definition

### ISSUE THREAD

**Issue by barryrowlingson** [rbertolusso/intubate#1]
This is a bit garbage-in-garbage-out but should probably be trapped:

Intubating to an object that doesnt conform to the `ntbt_foo` pattern causes C stack errors:

```
> x = ntbt_function_formula_data
> x(1,2)
Error: C stack usage  7969616 is too close to the limit
```

Perhaps it should check if the name is of the correct form, or maybe dump the magic and implement

`x = ntbt_function_formula_data(foo)`

which you could even write:

`x = foo %>% ntbt_function_formula_data`

Or something. C stack errors are bad....

**Comment by rbertolusso** [comment]
Thanks for the catch! Addressed. Please check.
Cheers, Roberto

**Comment by rbertolusso** [comment]
Seems working now. Thanks barryrowlingson
