### ISSUE TITLE
view()

### ISSUE THREAD

**Issue by krlmlr** [rbertolusso/intubate#2]
Would be great to have a version of `View()` that returns its input invisibly, see https://github.com/hadley/tibble/issues/130. This should be true for all other impure functions (e.g., `print()` ) if you choose to support them in your package.

**Comment by rbertolusso** [comment]
I am not sure if I follow you. 

These days `intubate` seems more appropriate for functions that have at least
two parameters (such as formula and data in that order), where you need to reverse them as pipes
send data as first parameter.

Let's see... `View` has only one parameter (same with `print`).

You want something in the line of ?

``` r
ntbt_function_arg <- function(arg, ...) {
   <name>(arg, ...)       ## Meaning <name> will translate to the name of the function to interface
   invisible(arg)
}
```

to then use it as

``` r
ntbt_print <- ntbt_function_arg

x <- 1:10
x %>%
  ntbt_print() %>%
  summary()
```

Please let me know if I interpret you correctly.

If yes, I think it may work. Something behind my head
tells me there could be some problems, and I need to
think more about it. 

But first please confirm we are in sync. Cheers, Roberto

**Comment by krlmlr** [comment]
Yes, that's the idea: call View(), and return the input invisibly. There may be other functions called for their side effects ("impure" functions) that also don't return their input and are not suitable for a pipe.

Additional work may be needed to make this work in RStudio, because utils::View() is shadowed. Perhaps the value of View can be looked up when the package is loaded (I haven't tested that)?

``` r
get("View", envir = .GlobalEnv)
```

**Comment by rbertolusso** [comment]
OK. Good to know I got it right. I will be for some days without Internet access, but I will be thinking about including these kind of functions that return NULL (by the way, can you confirm that all the functions that do not return a value, return NULL? - I mean, none return NA or anything else? I have some ideas but I want to be sure about this and I try to be as lazy as I can).

 I will concentrate, for example, in solving `print`. I have to think also in how to solve `plot` (that has a version with formula, but it would be good to also take care of the alternatives). Again, I have some ideas I want to see how they fly.

 Please, try to find out about the issue with `utils::View()` (of which I have no clue whatsoever and if possible I would not want to have to have any...), that seems important to you. I will concentrate in the general solution. Please help with this particular issue (shadowing and such...).

**Comment by krlmlr** [comment]
@jjallaire: When I'm in RStudio, the View() function that I can access from the global environment lives _somewhere_. What's the most reliable way to wrap View() from a package?

I was thinking about accessing the function pointer via

``` r
get("View", envir = .GlobalEnv)
```

but perhaps you can hint at something better.

**Comment by jjallaire** [comment]
Yes, that would be the best way.

**Comment by rbertolusso** [comment]
Please try the following and tell me if it puts (or not) a smile on your face.

``` r
function_... <- function(...) ..1

## Functions with any number of parameters.
ntbt_function_... <-  function(...) {
    Call <- match.call()
    Call[[1]] <- get_function_name(as.character(Call[[1]]))
    if (is.null(ret <- eval(Call, envir = parent.frame())))
      return (invisible(..1))
    ret
  }

ntbt_print <- ntbt_View <- ntbt_function_...

CO2 %>%
  ntbt_print() %>%
  ntbt_View() %>%
  summary()
```

I may not check for a number of days (I will be with no Internet access).

**Comment by krlmlr** [comment]
Thanks. I'd prefer if this consistently returned the first argument. What is the purpose of the `function_...` function?

**Comment by rbertolusso** [comment]
If the function returns returns consistently NULL, the first argument will be returned consistently. You would use this in those cases only (View, print, cat, ...). You can of course change it slightly to serve your purposes. 
function_... is just there for if you call directly ntbt_function_..., so it simply forwards without throwing an error.

**Comment by krlmlr** [comment]
> If the function returns returns consistently NULL, the first argument will be returned consistently.

If I care about the original return value, I call the original function. All I need here is consistent pipe-friendly behavior, that's the scope of this package, right? Would you please reconsider?

> function_... is just there for if you call directly ntbt_function_..., so it simply forwards without throwing an error.

I just don't see it used anywhere, is it meant to be by the end user?
