### ISSUE TITLE
ntbt_function_* functions fail if you use ::

### ISSUE THREAD

**Issue by richierocks** [rbertolusso/intubate#5]
The positions in the call are wrong, and give an unclear error message, if you use `intubate::`.  To reproduce:

``` r
.lm <- function(data, formula, ...) intubate::ntbt_function_formula_data(data, formula, ...)
CO2 %>% .lm(uptake ~ conc)
## Error in get_function_name(as.character(Call[[1]])) : 
##   :: is an invalid name.
## The interface should be named xtbt_<name>
## where <name> is the name of the function to be interfaced.intubate is an invalid name.
## The interface should be named xtbt_<name>
## where <name> is the name of the function to be interfaced.ntbt_function_formula_data is an invalid ## name.
## The interface should be named xtbt_<name>
## where <name> is the name of the function to be interfaced.
## In addition: Warning message:
## In if (gsub("(ntbt_).+", "\\1", ntbt_name) != "ntbt_") stop(paste0(ntbt_name,  :
##   the condition has length > 1 and only the first element will be usedError 
```

**Comment by rbertolusso** [comment]
I tried a couple of things and did not get it right. I will be out some days without Internet,
but I will be trying.
Could you please put me in context of why you would like to do this? You know, I am
too involved in what I want to achieve that I cannot grasp the purpose of it (well, it is almost 3am here so I cannot grasp almost anything...).

**Comment by rbertolusso** [comment]
I think I got it. I had no idea! Thank you for exposing me to such interesting situation.
Please check.

**Comment by richierocks** [comment]
This works, but there are a couple of things that I noticed.
1. After you've used `match.call`, all the arguments are named, so as far as I can tell, you don't need to swap the order of arguments 2 and 3.  (Best test this properly.)
2. In `get_function_name` change `xtbt_<name>` to `ntbt_<name>`.

**Comment by rbertolusso** [comment]
Try

``` r
ntbt_cor.test <- ntbt_function_formula_data  ## does swap order
try(ntbt_cor.test(data = USJudgeRatings, formula = ~ CONT + INTG))

try(ntbt_cor.test(formula = ~ CONT + INTG, data = USJudgeRatings))

ntbt_cor.test <- ntbt_lm                     ## does *not* swap order
try(ntbt_cor.test(data = USJudgeRatings, formula = ~ CONT + INTG))

try(ntbt_cor.test(formula = ~ CONT + INTG, data = USJudgeRatings))
```

You can read in the README

### Other nightmares around the corner

for discussion on this

**Comment by rbertolusso** [comment]
Corrected 2.
