### ISSUE TITLE
Please add link to setter pkg

### ISSUE THREAD

**Issue by richierocks** [rbertolusso/intubate#6]
I've added a link to _intubate_ in the README of my [_setter_](https://bitbucket.org/richierocks/setter) package, since the two packages have related goals.  Please can you add a reciprocal link in the README of _intubate_; I think it would be useful for your users.

**Comment by rbertolusso** [comment]
Sure. Please send me a sentence with the description that better serves your purposes.
I will be out for some days without Internet.

**Comment by richierocks** [comment]
Here you go:

```
The [*setter*](https://bitbucket.org/richierocks/setter) package contains mutators to set attributes of variables, that work well in a pipe (much like `stats::setNames())`.
```

**Comment by rbertolusso** [comment]
Done
