### ISSUE TITLE
install fails finegray not available from namespace:survival

### ISSUE THREAD

**Issue by timelyportfolio** [rbertolusso/intubate#8]
Just in case someone runs into this, I needed to upgrade my `survival` package.  Should you update DESCRIPTION to require the latest version?

```
==> Rcmd.exe INSTALL --no-multiarch --with-keep.source intubate

* installing to library 'C:/Users/Kent.TLEAVELL_NT/Documents/R/win-library/3.2'
* installing *source* package 'intubate' ...
** R
** inst
** preparing package for lazy loading
Error : object 'finegray' is not exported by 'namespace:survival'
ERROR: lazy loading failed for package 'intubate'
* removing 'C:/Users/Kent/Documents/R/win-library/3.2/intubate'

Exited with status 1.
```

**Comment by rbertolusso** [comment]
Truth is `intubate` does not require any library beyond `base` if it weren't for the examples. I just put a \dontrun on all the examples of `survival` and removed the dependency on DESCRIPTION and NAMESPACE. In the future we may talk about some ideas of what I would like to do with the examples in general. Thanks!

**Comment by timelyportfolio** [comment]
Might be that I was building with Ctrl + shift + b.  This gave error for ife and pls which I did not have installed and the error I mentioned.

**Comment by timelyportfolio** [comment]
Was confused.  I see your change now.  Check.

**Comment by timelyportfolio** [comment]
Well, actually, I just tried on a different computer and all the `Imports` are installed if not already available, so wrapping in `\dontrun` does not prevent the install.

**Comment by rbertolusso** [comment]
Got it. I will leave this open so I get back to it later. Thanks for you support!

**Comment by rbertolusso** [comment]
Dependencies from _all_ packages that have interfaces have been removed.
